#! /bin/sh

bspc monitor -d I II III IV V

bspc config border_width           2
bspc config window_gap             8

bspc config split_ratio            0.5
bspc config borderless_monocle     true
bspc config single_monocle 	       true

bspc config normal_border_color    "#19191C"
bspc config focused_border_color   "#F9FF85"

killall -9 sxhkd polybar picom
sxhkd &
$HOME/.config/polybar/launch.sh &
picom -b --config ~/.config/picom/picom.conf
feh $(find ~/.config/feh -type f | shuf -n 1) --no-fehbg --no-xinerama --bg-max &
